package guerer.example;

import java.util.HashMap;
import java.util.Map;

/*
 *  Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.


 */
public class FindTheDifference {
	public char findTheDifference(String s, String t) {
		Map<Character, Integer> map = new HashMap<Character, Integer>();
		for (char c : s.toCharArray()) {
			Integer tmp = map.get(c);
			map.put(c, tmp == null ? 1 : tmp + 1);
		}
		for (char c : t.toCharArray()) {
			Integer tmp = map.get(c);
			if (tmp == null || tmp == 0) {
				return c;
			} else {
				map.put(c, tmp - 1);
			}
		}
		return 'a';
	}
}
